version: '3.7'
services:

  hendrix:
    # The official v2 Traefik docker image
    image: traefik:${TRAEFIK_VERSION:-v2.8}
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    # labels:
    #   traefik.enabled: True
    #   traefik.http.routers.hendrix.entrypoints: http
    #   traefik.http.services.hendrix.loadbalancer.server.port: 8080
    #   traefik.http.routers.hendrix.rule: Host(`hendrix.$HOSTNAME_TLD`)
  khazad-dum: # https://hub.docker.com/_/vault
    image: vault:${VAULT_VERSION:-latest}
    restart: unless-stopped
    cap_add: 
      - IPC_LOCK
    volumes:
      - './_vault/logs:/vault/logs'
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8500
    ports:
      - 8500:8500
    labels:
      traefik.enabled: True
      traefik.http.routers.khazad-dum.entrypoints: http
      traefik.http.services.khazad-dum.loadbalancer.server.port: 8500
      # traefik.http.routers.khazad-dum.rule: Host(`.$HOSTNAME_TLD`)
  enki:
    image: 'gitlab/gitlab-ce:${GITLAB_VERSION:-latest}'
    restart: unless-stopped
    # TODO: Either configure correct values for enternal_url and hostname for prod or make them configurable 
    # hostname: 'localhost:80' # 'gitlab.symbionic.tech' 
    environment:
      GITLAB_OMNIBUS_CONFIG: | # TODO: Configure Gitlab https://docs.gitlab.com/ee/install/docker.html#pre-configure-docker-container
        external_url 'http://enki.$HOSTNAME_TLD'
        # Add any other gitlab.rb configuration here, each on its own line
    # ports:
    #   - '81:80'
    #   - '444:443'
    #   - '22:22'
    volumes:
      - ${GITLAB_HOME:?err}/config:/etc/gitlab
      - ${GITLAB_HOME:?err}/logs:/var/log/gitlab
      - ${GITLAB_HOME:?err}/data:/var/opt/gitlab
    shm_size: '256m'
    labels:
      traefik.enabled: True
      # traefik.http.routers.enki.rule: Host(`enki.$HOSTNAME_TLD`)
      traefik.http.routers.enki.entrypoints: http
      traefik.http.services.enki.loadbalancer.server.port: 80