services:
  # template:
  #   container_name: template # This becomes the subdomain used by traefik
  #   image: test:${SERVICE_VERSION:-v0.0} # Allow for supplying an override in the env but supply a default
  #   restart: unless-stopped
  #   labels:
  #     traefik.enable: true
  #     traefik.http.routers.hendrix.entrypoints: websecure
  #     traefik.http.routers.hendrix.tls: true
  #     traefik.http.services.hendrix.loadbalancer.server.port: <port>
  hendrix:
    container_name: hendrix
    environment:
      HOSTNAME_TLD: '${HOSTNAME_TLD:?err}'
      HTTPS_EMAIL: '${HTTPS_EMAIL:?err}'
      LINODE_TOKEN: '${TLS_LINODE_TOKEN:?err}'
    # restart: unless-stopped
    image: traefik:${TRAEFIK_VERSION:-v3.1}
    labels:
      traefik.enable: True
      traefik.http.routers.hendrix.entrypoints: websecure
      traefik.http.routers.hendrix.service: api@internal
      traefik.http.routers.hendrix.tls: true
      traefik.http.services.hendrix.loadbalancer.server.port: 8080
    ports:
      - '80:80'
      - '443:443'
      # TODO: Look into hardening the docker network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # So that Traefik can listen to the Docker events
      - ./traefik/config/traefik.yml:/etc/traefik/traefik.yml:ro # Static config
      - ./traefik/config/dynamic.yml:/etc/traefik/dynamic.yml:ro # Dynamic config
      - ./traefik/letsencrypt:/letencrypt:rw # Folder for letsencrypt to handle auto signing tls
      - ./traefik/local_certs:/certs # Folder for certs used in local testing

  whoami:
    container_name: whoami
    image: traefik/whoami
    labels:
      traefik.enable: True
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.tls: True
      traefik.http.services.whoami.loadbalancer.server.port: 80

  # khazad-dum: # https://hub.docker.com/_/vault
  #   image: vault:${VAULT_VERSION:-latest}
  #   restart: unless-stopped
  #   cap_add:
  #     - IPC_LOCK
  #   volumes:
  #     - './_vault/logs:/vault/logs'
  #   environment:
  #     VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8500
  #   ports:
  #     - 8500:8500
  #   labels:
  #     traefik.enable: True
  #     traefik.http.services.khazad-dum.loadbalancer.server.port: 8500
  # tyche:
  #   image: postgres:14.3
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=randompassword
  #     - POSTGRES_DB=PASS
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
  #   labels: # TODO: figure out what we are doing here since this is not serving to 80
  #     traefik.enable: True
  #     # traefik.http.services.khazad-dum.loadbalancer.server.port: 8500
  # enki:
  # image: 'gitlab/gitlab-ce:${GITLAB_VERSION:-latest}'
  # restart: unless-stopped
  # hostname: 'enki.${HOSTNAME_TLD:?err}'
  # environment:
  #   HOSTNAME_TLD: ${HOSTNAME_TLD:?err}
  #   GITLAB_OMNIBUS_CONFIG: | # TODO: Configure Gitlab https://docs.gitlab.com/ee/install/docker.html#pre-configure-docker-container
  #     external_url 'http://enki.$HOSTNAME_TLD'
  #     # Add any other gitlab.rb configuration here, each on its own line
  # volumes:
  #   - ${GITLAB_HOME:?err}/config:/etc/gitlab
  #   - ${GITLAB_HOME:?err}/logs:/var/log/gitlab
  #   - ${GITLAB_HOME:?err}/data:/var/opt/gitlab
  # shm_size: '256m'
  # labels:
  #   traefik.enable: True
  #   traefik.http.services.enki.loadbalancer.server.port: 80
  # astarte:  JS website
  #   image
  # tangaroa:
  #   image
version: '3.7'
