version: '3.7'
services:

  traefik:
    # The official v2 Traefik docker image
    image: traefik:${TRAEFIK_VERSION:-v2.8}
    ports:
      # The HTTP port
      - "80:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enabled: True
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.http.routers.traefik.rule: Host(`hendrix.$HOSTNAME_TLD`)
  vault: # https://hub.docker.com/_/vault
    image: vault:${VAULT_VERSION:-latest}
    restart: unless-stopped
    cap_add: 
      - IPC_LOCK
    volumes:
      - './_vault/logs:/vault/logs'
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8500
    ports:
      - 8500:8500
    labels:
      traefik.enabled: True
      traefik.http.routers.vault.entrypoints: http
      traefik.http.services.vault.loadbalancer.server.port: 8500
      traefik.http.routers.vault.rule: Host(`khazad-dum.$HOSTNAME_TLD`)
  gitlab:
    image: 'gitlab/gitlab-ce:${GITLAB_VERSION:-latest}'
    restart: unless-stopped
    # TODO: Either configure correct values for enternal_url and hostname for prod or make them configurable 
    # hostname: 'localhost:80' # 'gitlab.symbionic.tech' 
    environment:
      GITLAB_OMNIBUS_CONFIG: | # TODO: Configure Gitlab https://docs.gitlab.com/ee/install/docker.html#pre-configure-docker-container
        external_url 'http://enki.$HOSTNAME_TLD'
        # Add any other gitlab.rb configuration here, each on its own line
    # ports:
    #   - '81:80'
    #   - '444:443'
    #   - '22:22'
    volumes:
      - ${GITLAB_HOME:?err}/config:/etc/gitlab
      - ${GITLAB_HOME:?err}/logs:/var/log/gitlab
      - ${GITLAB_HOME:?err}/data:/var/opt/gitlab
    shm_size: '256m'
    labels:
      traefik.enabled: True
      traefik.http.routers.gitlab.rule: Host(`enki.$HOSTNAME_TLD`)
      traefik.http.routers.gitlab.entrypoints: http
      traefik.http.services.gitlab.loadbalancer.server.port: 80